# Generated by Django 4.2.2 on 2023-08-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Companyname',
            field=models.CharField(default='Construct', max_length=250),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(default='Madurai', max_length=150),
        ),
    ]
